version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sheedhet-server-redis
    ports:
      - '6379:6379'
  web:
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/sheedhet-server
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - '.env'

