version: '3'
services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass sheedhet-server-redis
    ports:
      - '6379:6379'

  web:
    build: .
    # entrypoint:
    #   - "/tmp/docker-web-entry.sh"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/sheedhet-server
    ports:
      - "3000:3000"
    depends_on:
      - redis
    env_file:
      - '.env'

  webpacker:
    build: .
    env_file:
      - '.env.docker'
    # entrypoint:
    #   - "/tmp/docker-webpacker-entry.sh"
    command: ./bin/webpack-dev-server --host 0.0.0.0
    volumes:
      - .:/sheedhet-server
    depends_on:
      - web
    ports:
      - '3035:3035'
